package server_options

import (
	"flag"
	"fmt"
)

type ServerOptions struct {
	DatabasePath string
	Port         int
}

func NewServerOptions(databasePath string, port int) *ServerOptions {
	return &ServerOptions{
		DatabasePath: databasePath,
		Port:         port,
	}
}

// Keep in sync with 'proxy' port in ui/package.json:
const DefaultPort = 8080

const DefaultDatabasePath = "gohuedata.db"

func ParseOptions() *ServerOptions {
	var databasePath string
	flag.StringVar(&databasePath, "db", DefaultDatabasePath, "Path to the SQLite database file containing your "+
		"Philips Hue data, as generated by gohuedata. Defaults to "+DefaultDatabasePath+".")

	var port int
	flag.IntVar(&port, "p", DefaultPort, fmt.Sprintf("Port to run the server on. Defaults to %d.", DefaultPort))

	flag.Parse()

	return NewServerOptions(databasePath, port)
}

func (o *ServerOptions) Address() string {
	return fmt.Sprintf(":%d", o.Port)
}
